version: '3'

services:
  # Development service
  dev:
    image: node:18
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  
  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  node_modules: