services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # The command is now in Dockerfile.dev
    volumes:
      # Mount the entire project directory into the container
      - .:/app
      # Use a named volume to prevent the host's node_modules from overwriting the container's
      # This also persists node_modules between container runs for faster startup
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - NODE_ENV=development
      # Polling is often necessary for hot-reloading to work reliably in Docker, especially on Windows/WSL
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      # Fix for Windows pathing issues in Docker
      - DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus-docker
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  node_modules: