import React, { useEffect, useState } from 'react';
import Layout from '@theme/Layout';
import { useHistory } from '@docusaurus/router';
import BrowserOnly from '@docusaurus/BrowserOnly';

// The ForceGraph2D component is dynamically imported to ensure it only runs on the client.
const ForceGraph2D = React.lazy(() =>
  import('react-force-graph').then((module) => ({ default: module.ForceGraph2D })),
);

function Graph() {
  const [graphData, setGraphData] = useState({ nodes: [], links: [] });
  const history = useHistory();

  useEffect(() => {
    // Fetch the graph data generated by our script
    fetch('/MassEdu/graph.json')
      .then((res) => res.json())
      .then((data) => setGraphData(data));
  }, []);

  const handleNodeClick = (node) => {
    // Navigate to the document's page when a node is clicked
    history.push(node.path);
  };

  return (
    <BrowserOnly fallback={<div>Loading graph...</div>}>
      {() => (
        <React.Suspense fallback={<div>Loading graph component...</div>}>
          <ForceGraph2D
            graphData={graphData}
            nodeLabel="title"
            nodeAutoColorBy="group"
            linkDirectionalArrowLength={3.5}
            linkDirectionalArrowRelPos={1}
            onNodeClick={handleNodeClick}
          />
        </React.Suspense>
      )}
    </BrowserOnly>
  );
}

export default function GraphPage() {
  return (
    <Layout title="Network Graph" description="Interactive graph of all concepts">
      <Graph />
    </Layout>
  );
}
